
# Genome to be annotated (Assembly, GFF3 and corresponding protein fasta file)
# Path to directory with samples directory contained genome.fasta, genome.gff3 and genome_prot.fna/fasta files
SAMPLES: /shared/home/sravel/glp701/annot_func/SAMPLES/
OUTPUT: /shared/home/sravel/glp701/annot_func/
# Function transfer based on sequence similarity 
# The list is ordered according to the trust given to the database. 
# 
blast_databases:
  SwissProt : "/shared/bank/uniprot_swissprot/current/fasta/uniprot_swissprot.fsa"
  TrEMBL: "/shared/bank/uniprot/current/fasta/uniprot_trembl.fasta"


#Should be DL from https://busco-data.ezlab.org/v5/data/lineages/ and uncompress    
busco_path: "/shared/projects/glp701/GLP701/db/"
lineage: "capnodiales_odb10"

# Method for the protein similarity search (1 for diamond, 0 for blastp)
use_diamond: 1

# GFF3 Tag corresponding to sequence identifier (input_proteome)
# Allowed values are: ID, Name, locus_tag
# Require for GFF3 enrichment
tag: "ID"

# 0 Only perform functional annotation (BLAST/Diamond + InterProScan)
# 1 For filter and check annotation quality ( filter transposable element genes and doubtful genes),
# refer to https://gitlab.southgreen.fr/hub/vaniseq/-/wikis/Gene-Filtering-VANPL_CR0040_3300M_all_ctg
only_reannotate: 0

# 
blast_repeat_database:
  repbase: "/shared/projects/glp701/annot_func/db/RepBase27.03.fasta/fugrep.ref"

hmm_databases:
  Retro_gag: "db/Retrotran_gag_3.hmm"
  retro_gypsy: "db/Transposase_28_Gypsy.hmm"

keywork_to_remove:
  - "Retrotrans_gag"
  - "polyprotein"
  - "Gag.Pol"
  - "Gypsy"
  - "Copia"
  - "Reverse transcriptase"
  - "transpos"
  - "elomer"
  - "Elongation factor"
  - "EF-Ts"

ipro_term_to_remove:
  - "IPR000123"
  - "IPR015706"
  - "IPR013103"
  - "IPR003036"
  - "IPR002079"
  - "IPR004004"
  - "IPR003141"
  - "IPR005162"
  - "IPR000721"
  - "IPR014817"
  - "IPR014834"
  - "IPR016195"
  - "IPR015699"
  - "IPR004312"
  - "IPR001584"
  - "IPR004332"
  - "IPR004028"
  - "IPR004957"
  - "IPR003545"
  - "IPR018289"

# Split FASTA into 10 files (increase/decrease this value if need, 5000 sequence for each part is recommended) 
fasta_split_number: 9

# Threads
params:
  global_blast_threads: 14
  interproscan_threads: 14
  global_diamond_threads: 14
  busco_threads: 10 

# Use envmodules (muse-login01)
modules:
  samtools: "samtools"
  hmmer: "hmmer"
  blast: "blast"
  interproscan: "interproscan"
  seqkit: "seqkit"
  diamond: "diamond"
  func_annot: "functional_annotation"
  gffread: "gffread"
  busco: "busco"
  R: "R/packages/4.1.0"
